main: dev.by1337.fparticle.Main
name: FParticleDumper
version: 1.5
author: By1337
api-version: "1.16"
website: 'https://github.com/By1337/FastParticle'
commands:
  fparticleDump:
    aliases:
      - fpd